# Generated by Django 4.0.6 on 2022-08-15 05:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('Wallet', models.IntegerField(blank=True, null=True)),
            ],
            managers=[
                ('variable', django.db.models.manager.Manager()),
            ],
        ),
    ]
