# Generated by Django 4.0.6 on 2022-08-22 09:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkSnackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            managers=[
                ('variable', django.db.models.manager.Manager()),
            ],
        ),
    ]
