# Generated by Django 4.0.6 on 2022-08-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkSnackApp', '0002_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
